version: '2'

networks:
    internal:
        driver: bridge

services:
  messagebus:
    build: .
    volumes:
    - .:/app
    networks:
        internal:
           aliases:
             - messagebus
  rabbitmq:
    image: rabbitmq:latest
    hostname: rabbit
    ports:
      - "5672:5672"
    networks:
        internal:
           aliases:
             - rabbit
